name: healthid_mama
description: Hackathon prototype for HealthID Mama (Flutter + Provider)
publish_to: "none"
version: 0.2.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  signature: ^5.4.0

flutter:
  uses-material-design: true
